=== acabey/acabey.github.io/projects/engineering.purdue.edu/scriptingwithobjects/swocode/chap17/SubEleRelSchema.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"      
      targetNamespace="http://AAAnamespace"                    
      xmlns:aaa="http://AAAnamespace"
      elementFormDefault="qualified">                          <!-- A -->
    <xsd:element name="AAA">                                   <!-- B -->
        <xsd:complexType>                                      <!-- C -->
            <xsd:sequence>                                     <!-- D -->
                <xsd:element name="BBB" type="xsd:string" />   <!-- E -->
                <xsd:element name="CCC" 
                               type="xsd:normalizedString" />  <!-- F -->
                <xsd:element ref="aaa:DDD" />                  <!-- G -->
            </xsd:sequence>                                
            <xsd:attribute name="xx" 
                       type="xsd:nonNegativeInteger" />        <!-- H -->
        </xsd:complexType>                                     <!-- I -->
    </xsd:element>                            
    <xsd:element name="DDD">                                   <!-- J -->
        <xsd:complexType>                                      
            <xsd:choice>                                       <!-- K -->
                <xsd:element name="EEE" type="xsd:anyURI" />   <!-- L -->
                <xsd:element name="FFF" type="xsd:date" />     <!-- M -->
                <xsd:element ref="aaa:GGG" />
            </xsd:choice>                                      <!-- N -->
            <xsd:attribute name="xx" use="optional" 
                                      type="xsd:byte" />       <!-- O -->
        </xsd:complexType>                               
    </xsd:element>                                       
    <xsd:element name="GGG">                                   <!-- P -->
        <xsd:complexType>                                
            <xsd:all>                                          <!-- Q -->
                <xsd:element name="HHH" />                     <!-- R -->
                <xsd:element name="III" />                     <!-- S -->
                <xsd:element name="JJJ" />                     <!-- T -->
            </xsd:all>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== acabey/acabey.github.io/projects/demos/engineering.purdue.edu/scriptingwithobjects/swocode/chap17/TestSchema2.xml
<?xml version="1.0"?>
<AAA xmlns="http://AAAnamespace"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://AAAnamespace SubEleRelSchema.xsd"
     xx="45">
    <BBB>qq</BBB>
    <CCC>1      2</CCC>
    <DDD>
        <GGG>
            <JJJ />
            <HHH />    
            <III />
        </GGG>
    </DDD>
</AAA>
